kind: pipeline
name: docker

steps:
- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: rancherlabs/rancher-catalog-stats
    tags: latest
  when:
    instance:
      - drone-publish.rancher.io
    ref:
      include:
        - "refs/heads/*"
        - "refs/tags/*"
        - "refs/pull/*"
    event:
      - push
      - tag

