{
 "title": "catalog",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "influxcatalog", "query": "influxdb" },
   { "name": "agg_time", "query": "1h,4h,12h,24h" }
  ]
 },
 "panels": [
  {
   "title": "World map",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rancher unique IP requests",
     "type": "grafana-worldmap-panel",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 1 },
     "valueName": "total",
     "targets": [
      {
       "alias": "$tag_country_isocode",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "country_isocode" ], "type": "tag" }
       ],
       "measurement": "byCountry_1h",
       "query": "SELECT sum(\"unique\") FROM byCountry_$agg_time WHERE \"path\" =~ /\\/repos\\/rancher-catalog/ OR \"path\" = '/rancher-catalog.git/info/refs?service=git-upload-pack' OR  \"path\" =~ /\\/repos\\/charts/ AND $timeFilter GROUP BY time($__interval), \"country_isocode\"",
       "select": [
        [
         { "params": [ "unique" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        {
         "key": "path",
         "operator": "=",
         "value": "/rancher-catalog.git/info/refs?service=git-upload-pack"
        }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Rancher unique IP requests v1.x",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "requests_1h",
     "query": "SELECT sum(unique_ip) FROM byUid_$agg_time WHERE \"path\" =~ /rancher-catalog/ AND $timeFilter GROUP BY time($agg_time)",
     "select": [
      [
       { "params": [ "unique" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      {
       "key": "path",
       "operator": "=",
       "value": "/community-catalog.git/info/refs?service=git-upload-pack"
      }
     ]
    }
   ]
  },
  {
   "title": "Rancher unique UID requests v1.x",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "measurement": "requests",
     "query": "SELECT count(distinct(uid)) FROM byUid_history_$agg_time WHERE \"path\" =~ /rancher-catalog/ AND $timeFilter GROUP BY time($agg_time)",
     "select": [
      [
       { "params": [ "ip" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      {
       "key": "path",
       "operator": "=",
       "value": "/rancher-catalog.git/info/refs?service=git-upload-pack"
      }
     ]
    }
   ]
  },
  {
   "title": "Rancher unique IP requests v2.x",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "requests_1h",
     "query": "SELECT count(distinct(ip)) FROM byIp_$agg_time WHERE \"path\" =~ /\\/repos\\/rancher-catalog\\/commits\\/v2.0-(.*)/ OR \"path\" =~ /\\/repos\\/charts/  AND $timeFilter GROUP BY time($agg_time)",
     "select": [
      [
       { "params": [ "unique" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      {
       "key": "path",
       "operator": "=",
       "value": "/community-catalog.git/info/refs?service=git-upload-pack"
      }
     ]
    }
   ]
  },
  {
   "title": "Rancher unique UID requests v2.x",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "measurement": "requests",
     "query": "SELECT count(distinct(uid)) FROM byUid_history_$agg_time WHERE \"path\" =~ /\\/repos\\/rancher-catalog\\/commits\\/v2.0-(.*)/ OR \"path\" =~ /\\/repos\\/charts/ AND $timeFilter GROUP BY time($agg_time)",
     "select": [
      [
       { "params": [ "ip" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      {
       "key": "path",
       "operator": "=",
       "value": "/rancher-catalog.git/info/refs?service=git-upload-pack"
      }
     ]
    }
   ]
  },
  {
   "title": "Rancher total UID v1.x",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "measurement": "requests",
     "query": "SELECT count(distinct(\"uid\")) FROM byUid_$agg_time WHERE \"path\" =~ /\\/repos\\/rancher-catalog/ OR \"path\" = '/rancher-catalog.git/info/refs?service=git-upload-pack'  ",
     "select": [
      [
       { "params": [ "ip" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      {
       "key": "path",
       "operator": "=",
       "value": "/rancher-catalog.git/info/refs?service=git-upload-pack"
      }
     ]
    }
   ]
  },
  {
   "title": "Rancher total UID v2.x",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "measurement": "requests",
     "query": "SELECT count(distinct(\"uid\")) FROM byUid_history_$agg_time WHERE \"path\" =~ /\\/repos\\/charts/  OR \"path\" =~ /\\/repos\\/rancher-catalog\\/commits\\/v2.0-(.*)/ ",
     "select": [
      [
       { "params": [ "ip" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      {
       "key": "path",
       "operator": "=",
       "value": "/rancher-catalog.git/info/refs?service=git-upload-pack"
      }
     ]
    }
   ]
  },
  { "title": "Instant data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Unique requests by UID/path v1.x",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "community-catalog",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "path" ], "type": "tag" }
     ],
     "measurement": "requests_1h",
     "query": "SELECT count(distinct(uid)) FROM byUid_history_$agg_time WHERE \"path\" =~ /community-catalog/ AND $timeFilter GROUP BY time($agg_time) ",
     "select": [
      [
       { "params": [ "unique" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      {
       "key": "path",
       "operator": "=",
       "value": "/community-catalog.git/info/refs?service=git-upload-pack"
      },
      {
       "condition": "OR",
       "key": "path",
       "operator": "=",
       "value": "/rancher-catalog.git/info/refs?service=git-upload-pack"
      }
     ]
    },
    {
     "alias": "rancher-catalog",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(uid)) FROM byUid_history_$agg_time WHERE \"path\" =~ /rancher-catalog/ AND $timeFilter GROUP BY time($agg_time)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "byUid_history_24h",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "Unique requests by UID/path v2.x",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "community-catalog",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(uid)) FROM byUid_history_$agg_time  WHERE \"path\" =~ /\\/repos\\/community-catalog\\/commits\\/v2.0-(.*)/  AND $timeFilter GROUP BY time($agg_time) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "select tag value" }
     ]
    },
    {
     "alias": "rancher-catalog",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(uid)) FROM byUid_history_$agg_time  WHERE \"path\" =~ /\\/repos\\/rancher-catalog\\/commits\\/v2.0-(.*)/  AND $timeFilter GROUP BY time($agg_time) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "charts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(uid)) FROM byUid_history_$agg_time WHERE \"path\" =~ /\\/repos\\/charts/ AND $timeFilter GROUP BY time($agg_time) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "Unique requests by IP/path v1.x",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "community-catalog",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "path" ], "type": "tag" }
     ],
     "measurement": "requests_1h",
     "query": "SELECT sum(unique_ip) FROM byUid_$agg_time WHERE  \"path\" =~ /community-catalog/ AND $timeFilter GROUP BY time($agg_time)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      {
       "key": "path",
       "operator": "=",
       "value": "/community-catalog.git/info/refs?service=git-upload-pack"
      },
      {
       "condition": "OR",
       "key": "path",
       "operator": "=",
       "value": "/rancher-catalog.git/info/refs?service=git-upload-pack"
      }
     ]
    },
    {
     "alias": "rancher-catalog",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(unique_ip) FROM byUid_$agg_time WHERE \"path\" =~ /rancher-catalog/ AND $timeFilter GROUP BY time($agg_time) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Unique requests by IP/path v2.x",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "community-catalog v2.0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(ip)) FROM byIp_$agg_time WHERE \"path\" =~ /\\/repos\\/community-catalog\\/commits\\/v2.0-(.*)/ AND $timeFilter GROUP BY time($agg_time) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "rancher-catalog v2.0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(ip)) FROM byIp_$agg_time WHERE \"path\" =~ /\\/repos\\/rancher-catalog\\/commits\\/v2.0-(.*)/ AND $timeFilter GROUP BY time($agg_time) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "charts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(ip)) FROM byIp_$agg_time WHERE \"path\" =~ /\\/repos\\/charts/ AND $timeFilter GROUP BY time($agg_time) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Unique requests by IP/country v1.x",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" }
     ],
     "measurement": "requests_1h",
     "query": "SELECT sum(\"unique\") FROM byCountry_$agg_time WHERE \"path\" =~ /\\/repos\\/rancher-catalog/ OR \"path\" = '/rancher-catalog.git/info/refs?service=git-upload-pack' AND $timeFilter GROUP BY time($interval), \"country\"",
     "select": [
      [
       { "params": [ "unique" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      {
       "key": "path",
       "operator": "=",
       "value": "/rancher-catalog.git/info/refs?service=git-upload-pack"
      }
     ]
    }
   ]
  },
  {
   "title": "Unique requests by IP/country v2.x",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" }
     ],
     "measurement": "requests_1h",
     "query": "SELECT sum(\"unique\") FROM byCountry_$agg_time WHERE \"path\" =~ /\\/repos\\/community-catalog\\/commits\\/v2.0-(.*)/  OR \"path\" =~ /\\/repos\\/rancher-catalog\\/commits\\/v2.0-(.*)/ OR \"path\" =~ /\\/repos\\/charts/ AND $timeFilter GROUP BY time($interval), \"country\"",
     "select": [
      [
       { "params": [ "unique" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      {
       "key": "path",
       "operator": "=",
       "value": "/rancher-catalog.git/info/refs?service=git-upload-pack"
      }
     ]
    }
   ]
  },
  {
   "title": "Total requests by country v1.x",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" }
     ],
     "measurement": "requests_1h",
     "query": "SELECT sum(\"total\") FROM byCountry_$agg_time WHERE \"path\" =~ /\\/repos\\/rancher-catalog/ OR \"path\" = '/rancher-catalog.git/info/refs?service=git-upload-pack' AND $timeFilter GROUP BY time($interval), \"country\"",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      {
       "key": "path",
       "operator": "=",
       "value": "/rancher-catalog.git/info/refs?service=git-upload-pack"
      }
     ]
    }
   ]
  },
  {
   "title": "Total requests by country V2.x",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" }
     ],
     "measurement": "requests_1h",
     "query": "SELECT sum(\"total\") FROM byCountry_$agg_time WHERE \"path\" =~ /\\/repos\\/community-catalog\\/commits\\/v2.0-(.*)/  OR \"path\" =~ /\\/repos\\/rancher-catalog\\/commits\\/v2.0-(.*)/ OR \"path\" =~ /\\/repos\\/charts/ AND $timeFilter GROUP BY time($interval), \"country\"",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      {
       "key": "path",
       "operator": "=",
       "value": "/rancher-catalog.git/info/refs?service=git-upload-pack"
      }
     ]
    }
   ]
  }
 ]
}